### ISSUE TITLE
support azure blob storage on the azure cloud PoC

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-notebooks#1354]
**Disclaimer**: This is not about properly support Azure Blob storage, only for enabling it for a PoC to test it.

Add support for mounting Azure Blob storage in Sessions on the Azure PoC. We can repurpose the S3 fields in the UI and have a git branch of the notebooks service that uses them to mount blob storage instead of S3.

We probably need to install a custom CSI driver instead of datashim for this to work.

**Comment by olevski** [comment]
Relevant docs from Azure:
- https://learn.microsoft.com/en-us/azure/aks/azure-csi-blob-storage-dynamic
- https://learn.microsoft.com/en-us/azure/aks/azure-csi-blob-storage-static

This would have to be done most likely on the azure renku deployment... That is the easiest because the csi drivers there for this may just come installed in AKS. We can confirm this with YAT.
