### ISSUE TITLE
Refactor preStop hook to use ConfigMap

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-notebooks#137]
Move the `pre-stop.sh` script to a `ConfigMap` and mount it as new volume instead of adding it to the image.

addresses #130

**Comment by rokroskar** [comment]
Some more details: 

Recently we added a [`pre-stop.sh`](https://github.com/SwissDataScienceCenter/renku-jupyter/blob/master/docker/base/lifecycle/pre-stop.sh) script to the base renku image. This script is enabled as a [pre-stop lifecycle event handler](https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/) in this service. However, instead of having it in the image, we want to inject it into the containers as a [ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) so that it will get executed for any image. 

The changes required here are:

- [ ] add the configmap with the `pre-stop.sh` script to the user pod in `jupyterhub/spawners.py`
- [ ] remove the script from the [base renku jupyter image](https://github.com/SwissDataScienceCenter/renku-jupyter/tree/master/docker/base) (this needs a PR to that repo)
- [ ] test

**Comment by mohammad-sdsc** [comment]
These are some useful links:
https://stackoverflow.com/questions/41674108/how-to-include-script-and-run-it-into-kubernetes-yaml/50506354
https://gist.github.com/etoews/82c039843663de7e7f1e18bf4debe5fa
https://stackoverflow.com/questions/51124426/k8s-deployment-executing-shell-scripts-reading-configuration-data
