### ISSUE TITLE
[Environments] 500 error when connecting too quickly

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku-notebooks#257]
## Description

When connecting to a new environment as soon as its ready, a 500 error appears instead of the notebook (see screenshot)

## Reproduce

1. Start a new environment
2. As soon as the environment is ready, click on connect
3. A 500 Internal Server Error appears
4. When waiting some seconds and refreshing the error goes away and the notebook is loaded successfully

![notebook-notyet-available](https://user-images.githubusercontent.com/43743260/75584460-16963080-5a70-11ea-85fa-c79f69ae0e68.png)

**Outcome**
The user might mistakenly think that there's a problem with the notebook.

## Context

- renkulab: stable.dev.renku.ch
- os: linux
- browser: firefox

- reproduced on a mac as well

**Comment by lorenzo-cavazzi** [comment]
this was fixed by #253 

It may still occasionally happen that the JupyterLab page is opened 1-2 seconds before the environment is ready, but now the UX is different: the temporary page is the one below (see screenshot) and it redirects automatically the user to the proper page when the environment is up.

You can try it on https://lorenzotest.dev.renku.ch/

![Screenshot_20200303_110331](https://user-images.githubusercontent.com/43481553/75803122-2f5b5a80-5d7e-11ea-9a34-662784e09d62.png)
