### ISSUE TITLE
refactor: define models and schemas

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#421]
Currently all the JSON response and request parsing is ad-hoc. We should clearly define and test models and schemas. 

We are using marshmallow in other components so it seems to be a natural choice here as well. 

This would also resolve #71

**Comment by ableuler** [comment]
Good point, this would make further improvements and refactoring of this service a much safer undertaking. I think we have to define two concepts here:
- servers
- server-options
The `/logs/{server-name}` which are currently handled as a top-level resource should be refactored under `/servers/{server-name}/log` to be a bit more restful and also in line with the k8s API.

**Comment by rokroskar** [comment]
The logs endpoint was initially implemented as you suggest @ableuler but was changed in #188 (see #186). I don't exactly remember the discussion around that, maybe @lorenzo-cavazzi and @mohammad-sdsc can shed some light on why it was changed?

**Comment by lorenzo-cavazzi** [comment]
I honestly don't remember the reason behind it, but I believe the log endpoint was not used before that PR.
I think the `servers/{server-name}/logs` makes more sense than the current `log({server-name}`.

**Comment by mohammad-sdsc** [comment]
Same here, I don't remember why we considered logs as an independent resource.

**Comment by lorenzo-cavazzi** [comment]
From [this comment](https://github.com/SwissDataScienceCenter/renku-notebooks/pull/435#discussion_r510376645): we can take the occasion to re-structure the `server` resource. My proposal is

- [ ] Remove the `annotations` object and put all the `renku.io` prefixed resources in a `repository` (or `project`) object. The `hub.jupyter.org` prefixed data are redundant.
```
repository: {
    namespace: <value>,
    commit: <value>,
    ...
}
```
- [ ] Remove the `state` object. It contains only the `pod_name` that is not useful.
- [ ] The resources have eterogeneous formatting, coming from [k8s units for resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes), that the UI [tries to guess](https://github.com/SwissDataScienceCenter/renku-ui/blob/master/src/notebooks/Notebooks.present.js#L241-L249). I would standardize them in the notebooks API. CPU always in float number (1, 2, 0.1 are ok, 100m is not), RAM and storage in GB (8, 2, 0.5 are ok, 512Mi, 512M, 536870912, 5.12e8 are not), ...
- [ ] (nice to have) Simplify the `status` object. Currently, it comes straight from k8s and it's a bit confusing for the client. I think `message` should contain the combination of `message` and `reason`, while `step` should contain the combination of `phase`, `step` and `ready`. I can further expand on this if needed, providing the combinations we currently use in the UI.

**Comment by olevski** [comment]
Hey @ableuler, @pameladelgado, @rokroskar, @lorenzo-cavazzi here is my proposal on how we can tackle this:
- use marshmallow to deserialize requests and to serialize responses
- on deserialization of the parameters sent in a request we can also implement validation checks in the schemas
- The response serialization may not be strictly necessary because I think it is no different than just calling jsonify on a dictionary that is intended as the response, but it is good to use the marshmallow library here as well because it serves as a way to document the format of the response and as an internal check that we return what the UI expects
- I think my biggest concern is that we organize the API code well so that we can also make our job easier when we work on the API versioning (at some point).

Here is how I think we can organize the code:
- I think that we should split up the renku_notebooks/api/notebooks.py into one file for each specific endpoint and for the type of request too (i.e.  POST, GET, etc).
- This would result in a structure like
```
renku_notebooks/api/
  servers/
    root.py  # get, post on servers endpoint
    server_name.py  # get, delete on servers/<server_name>
    logs.py  # get on servers/logs/<server_name>, 
             # currently this is at logs/server_name but we will change it
  server_options/
    root.py  # get on server_options endpoint    
```
- Every .py file mentioned above would contain the endpoint function, request schema and response schema so you go to one place to see all the related code
- In terms of splitting the work between me and Pamela one person can work on the server_options endpoint and another on everything that is under the servers endpoint.

A question I have is whether we want to setup automatic generation of swagger files. It seems that marshmallow can do this but not directly out of the box. And we would have to install some additional packages/plugins (created by the same folks as marshmallow) and do some additional setup in the github actions.

Let me know what you think.

**Comment by lorenzo-cavazzi** [comment]
I think this is overall a great idea!

> The response serialization may not be strictly necessary [...]

I would make serialization on the response always mandatory. That would automatically verify that all the fields are in the response and it will handle standardization much better than any manual solution (e.g. in the custom image PR, we have some inconsistencies like `"True"` for a boolean value and mixed naming convention --> camel case, snake case, kebab case)

> I think that we should split up the renku_notebooks/api/notebooks.py into one file for each specific endpoint and for the type of request too (i.e. POST, GET, etc).

It seems a neat separation. Not sure I understand correctly here, but from the example, I assume you are proposing to keep different verbs in the same file (e.g. function for `GET /servers` and `POST /servers` on the same page). If this is correct, I totally like it.

> Every .py file mentioned above would contain the endpoint function, request schema and response schema so you go to one place to see all the related code

I generally find having schemas definition in a single file a better solution because it's easier to identify reusable sub-parts. Anyway, I'm not strongly opinionated on this (my point may even be bad for supporting versioning) and, unless others have my same view, I'm ok with your proposal.

> A question I have is whether we want to setup automatic generation of swagger files.

That would actually be very nice. I think the [core component in renku-python](https://github.com/SwissDataScienceCenter/renku-python/tree/master/renku/core) has already something similar in place. I would say that exposing it in Renkulab would make this solution very nice and terribly useful to developers consuming the APIs.

For the versioning, since we will usually only support 1 or 2 versions at the same time, should we always duplicate the whole function + schemas to avoid problems? Is there any common strategy for addressing this? Do you have something in mind?

**Comment by olevski** [comment]
@lorenzo-cavazzi I agree with all your suggestions above, except maybe keeping schemas in a separate file. I am just not sure if maybe the schemas and flaks endpoints should be in the same file because they are so closely related. I think this will be better resolved once I start implementing this. Moving the schemas around to different files will be easy so we can decide on this during code review.

Also in terms of versioning I would like to avoid making exact copies of any code. So schemas or functions that specify endpoints should be reused as much as possible.

**Comment by olevski** [comment]
As for getting swagger documentation automatically from the schemas and flask endpoints, things are not very straightforward. There are some other packages/frameworks (i.e. [Flask-RESTPlus](https://flask-restplus.readthedocs.io/en/stable/)) that are based on flask and support this but they use [class-based flask resources](https://flask.palletsprojects.com/en/1.1.x/views/#method-based-dispatching) (which we do not use). So I do not think it is worth re-formatting our code and committing to such flask extensions simply for the swagger documentation.

I have two ideas of how to proceed:

**1. Use [flask-apispec](https://flask-apispec.readthedocs.io/en/latest/)**

Pros:
- allows us to use our current setup where each endpoint is a decorated function
- it provides additional decorators to validate the request with a marshmallow schema (for this it uses a different library called webargs which is really nice and we should use)
- it automatically generates (and hosts on a flask endpoint) the swagger ui and swagger json file

Cons:
- The decorator to serialize the response does not enforce a schema at all, which is really weird. So even if the response schema is blatantly violated the response will be sent with no errors. To alleviate this we can make our own decorator or decorate the library's decorator to properly validate the response
- It is not actively developed (i.e. the maintainers do not add new features but say they will review PRs from users). Because of this I fear that a new version of flask, webargs or something else may completely break our automatic swagger documentation.
- It does not support OpenAPI v3, only v2

**2. Use webargs, apispec (i.e. the components of flask-apispec)**

Pros:
- We do not depend on a library like flask-apispec that is not actively maintained
- We have greater control over how the swagger documentation is generated and where/how it is served

Cons:
- We have to write more code to automate and generate the swagger documentation. The easiest way is to add yaml in the docstring of every endpoint that is parsed by apispec which then generates the proper swagger documentation.
- Generate and host the swagger ui / json or create a flask endpoint where this is available
- We have to write our own decorator for validating the response from a flask endpoint. This can be done with about 20 lines of code, I already tried in a small test case.

**3. A pretty extreme and risky option: Switch to a completely new framework called [FastAPI](https://fastapi.tiangolo.com/). This has automated swagger and redoc documentation. It also supports async code right out of the box. The API is very similar to flask but it uses a server such as Uvicorn or Hypercorn. 

I am leaning most toward option 2 with first only implementing the schemas in this issue and then having a separate issue to get the swagger documentation done. What do you think?

**Comment by rokroskar** [comment]
cc @jsam maybe we should sync on how some of this is handled in the renku-core service?

**Comment by olevski** [comment]
Ok I was a bit confused before and thought renku-python only contained the code for the renku cli, but that is not the case. I see that the flask-apispec package is used in the renku-core service. So I can just follow what they have done there.
