### ISSUE TITLE
endpoint for providing information about existing data to clients

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#584]
User sessions may end up with autosave branches or existing PVs, depending on how they are terminated. We should introduce an endpoint that tells clients whether either of those is available for a given user / namespace / project / commit combination.

**Comment by lorenzo-cavazzi** [comment]
Here is a proposal for the API: https://app.swaggerhub.com/apis/lorenzo-cavazzi/renku-notebooks/0.1.0

Basically, it is invoked per project and it returns a list of available autosaves. It also returns an indication of the backend support for PVS in thatRenkuLab deployment.

The information for each autosave includes commit, branch, pvs (boolean, whether it's a PVS or not), date. We can leave the date out from the first implementation. I thought it may be useful for the user to distinguish outdated content from potentially used autosaved code. For the GitLab branches, it should be easy (last commit date on the autosave branch), while I'm not sure if we can get the "last unmounted" or "last accessed" date in k8s.

**Comment by olevski** [comment]
@lorenzo-cavazzi this is currently implemented on my dev deployment. You can see the swagger page at https://tasko.dev.renku.ch/jupyterhub/services/notebooks/api/docs/.

I have a few questions:
1. If pvs support is enabled do we want to still show / check for autosave branches (some may be there before the pvc feature was added)?
2. The commit part of the response is supposed to show the commit that was backed up / recovered, and in the case of the autosave branches not the commit of the autosave itself?
3. For PVCs do we want to show pvcs that are part of a running session? I.e. these are currently being used so not a true 'autosave'.
4. The date part of the response represents when the autosave branch or pvc or autosave branch was created.

Currently the pvc support in the deployment is disabled (this is what I tested last). Earlier I tested pvcs and they work too. That is why I am asking question no 1. This will determine whether we show only pvcs, autosaves or both. I think that if pvcs are enabled for the deployment we show both pvcs and autosaves, but if pvcs are not supported we show only autosave branches.

**Comment by lorenzo-cavazzi** [comment]
1. Yes I would say so. Your last sentence seems the most reasonable solution to me (PVC + autosave if PVC enabled, only autosave otherwise).
2. That's correct. It's meant to be used to show the user some sort of feedback when starting a new environment from the same branch/commit combination, so we need the initial commit.
3. I would include them too, though it's not particularly relevant for the UI because we show different content for running environments
4. I think it's ok for the branches (though the creation date for the last commit in that branch may be a better choice since it should be "last time it was updated" -- not sure if they are always very close), while I'm not sure about PVC. If I created one a week ago and then I worked on it again yesterday, I would expect the date from yesterday as an indication for the autosave. Is it possible to bind it to the last time it was attached? Or even better, to the last time it was accessed?

P.S. I quickly tested on the Swagger you linked (it's so convenient to test the APIs there on the fly! Thanks again for implementing it :star_struck: ), and I noticed something unexpected in the `branch`

```
{
  "autosaves": [
    {
      "branch": "renku/autosave/lorenzo.cavazzi.tech/master/634de96/8eeb7a0",
      "commit": "8eeb7a06eff73a8eb2506971790ac287d4766fe4",
      "date": "2021-04-14T08:49:39+00:00",
      "pvs": false
    }
  ],
  "pvsSupport": false
}
```
I would expect the branch name from which the autosave branch was originated. In this case, it would be `"branch": "master"` instead of the full autosave name `"renku/autosave/lorenzo.cavazzi.tech/master/634de96/8eeb7a0"`

**Comment by olevski** [comment]
@lorenzo-cavazzi thanks. I will implement what you mentioned.

One more question. What do the two commit codes in the autosave branch name mean? 

For example for a branch name like this:
`renku/autosave/<username>/<branch>/634de96/8eeb7a0`

What is the difference between the two commit codes at the end? I imagine one is the original commit that this autosave was created for? What does the other one mean?

**Comment by lorenzo-cavazzi** [comment]
The first commit is the originating one (i.e. the one used when starting the environment), while the other is the final commit at the autosave time. When it's the same, it means there are no new commits but still there is some uncommitted work.

From this `renku/autosave/<username>/<branch>/<initial_commit>/<final_commit>`, the relevant information for the autosave endpoint is the `branch` and the `initial_commit`.

**Comment by olevski** [comment]
@lorenzo-cavazzi I resolved all the things you mentioned except the one about the timestamp. I have no way of telling when the pvc was last accessed or mounted. All I can get is when it was created. I will submit a PR shortly.

**Comment by lorenzo-cavazzi** [comment]
Ok, thanks for the info. Maybe we should remove that info altogether since I'm not sure how useful would be the initial creation date for the user.
Well, let's leave it as it is now, we can review it later. I'll review the PR soon
