### ISSUE TITLE
vim missing from defaut image

### ISSUE THREAD

**Issue by mitch-volpi** [SwissDataScienceCenter/renku-notebooks#86]
It would be cool to have vim pre-installed on the default image.

**Comment by leafty** [comment]
Why it's not there:
- jupyterlab can already open files like a text editor
- nano is installed
So the idea is that if you want vim, then it's because of the shortcuts and stuff and that means you are likely able to install it yourself.

You can comment if you disagree and we'll think about adding it to the pre-installed things.

**Comment by mitch-volpi** [comment]
Yeah I did, I opened the issue upon @rokroskar 's suggestion.

**Comment by rokroskar** [comment]
closed by https://github.com/SwissDataScienceCenter/renku-jupyter/commit/adfa504947df9689ca2e0014512a98f86e343fca
