### ISSUE TITLE
Add a `GET check_docker_image` endpoint

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-notebooks#989]
We should expose a new endpoint `check_docker_image` to allow clients to use [the logic implemented in the `image_exists` function](https://github.com/SwissDataScienceCenter/renku-notebooks/blob/master/renku_notebooks/util/check_image.py#L57) to verify if a docker image is available or not.

This endpoint should take a simple parameter `image_url` and return a simple JSON response
```
{
  available: <bool>
}
```

**Comment by olevski** [comment]
One thing that comes to mind is that we can make this a bit more REST-like. Because the notebook service is (at least trying to be) a REST api. So maybe we do something like `/notebooks/images/<image_url>` or `/notebooks/images` and then pass `image_url` as a parameter. The latter may be better because in the former case adding `<image_url>` in the url itself will require url encoding it or something like that.

But still then I can respond with a 404 if I cannot find the image, or I can respond with a 200 and some very short image info if I can find the image.
